{% set version = "1.0.1" %}

package:
    name: basic-illumination
    version: {{ version }}
source:
    -   git_url: https://github.com/labsyspharm/basic-illumination.git
        git_rev: {{ version }}
    -   url: https://www.helmholtz-muenchen.de/fileadmin/ICB/software/BaSiC/BaSiCPlugin.zip

build:
    number: '0'
    string: '0'

requirements:
    host:
        - openjdk >=8.0 
        - git

    run:
        - openjdk >=8.0 

        
about:
    home: https://github.com/labsyspharm/basic-illumination
    license: GNU General Public License
    summary: "ImageJ BaSiC shading correction for use with Ashlar."
